---
- name: Run cleanup when removing node
  ansible.builtin.include_tasks:
    file: cleanup.yaml
  when: remove_node | default(false)

- name: End play if removing node
  ansible.builtin.meta: end_host
  when: remove_node | default(false)

- name: Install DNS packages and directories
  ansible.builtin.include_tasks:
    file: install.yaml
  when:
    - target is undefined
    - task_type is undefined
    - not (remove | default(false))
    - not (remove_node | default(false))

- name: Configure DNS service
  ansible.builtin.include_tasks:
    file: configure.yaml
