---
- name: Install Looking Glass proxy prerequisites
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Configure Looking Glass proxy
  ansible.builtin.include_tasks:
    file: configure.yaml
