peers:
  - comment: 'factor2431'
    wg:
      port: 21534
      endpoint: 'jp-tyo.factor2431.com:21023'
      wg_pubkey: 'XYyk/uk3LTHk7vOqtDsDh/AcPtdT3qQptqhggzZCRio='
      psk: null
      peer4: null
      peer6: 'fe80::1534'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421534
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'tech9'
    wg:
      port: 21588
      endpoint: 'jp-tyo01.dn42.tech9.io:52923'
      wg_pubkey: 'unTYSat5YjkY+BY31Q9xLSfFhTUBvn3CiDCSZxbINVM='
      psk: null
      peer4: null
      peer6: 'fe80::1588'
      own6: 'fe80::100'
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421588
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'iyoroy'
    wg:
      port: 22024
      endpoint: 'ipv4.tyo-jp.ecs.iyoroy-infra.top:21023'
      wg_pubkey: 'Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4='
      psk: null
      peer4: null
      peer6: 'fe80::2024'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242422024
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'iedon'
    wg:
      port: 22189
      endpoint: 'jp-ty2.dn42.iedon.net:57739'
      wg_pubkey: 'XjKsLfOYJ8y/U9saLpfM/MjXErlQ7gkw3+OgQTdVZ0U='
      psk: null
      peer4: null
      peer6: 'fe80::2189:115'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242422189
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'lare'
    wg:
      port: 23035
      endpoint: 'jp01.dn42.lare.cc:21023'
      wg_pubkey: 'oTPdRylNhX2O80e6rLejT9Fwzo7KWKZ7a3PUF4G9oEM='
      psk: null
      peer4: null
      peer6: 'fe80::3035:134'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423035
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    removed: true
  - comment: 'cowgl'
    wg:
      port: 23999
      endpoint: 'tyo.node.cowgl.tech:31023'
      wg_pubkey: 'mMGGxtEqsagrx1Raw57C2H3Stl6ch/cUuF7y08eVgBE='
      psk: null
      peer4: null
      peer6: 'fe80::1:3999'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423999
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'Stevie'
    wg:
      port: 20337
      endpoint: 'tyo01.dn42.wwrr.ru:21023'
      wg_pubkey: 'xZBEeAO1btrRvU7cpXTBqaw8CZsmxrfB0005OgljtmU='
      psk: null
      peer4: null
      peer6: 'fe80::337'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420337
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'qiuxin'
    wg:
      port: 21771
      endpoint: 'tyo1.exploro.one:32619'
      wg_pubkey: 'MhxNjov4q8GjBFhDhSX4G8Zzx7/w4qbWw2RQSU5JDTU='
      psk: null
      peer4: null
      peer6: 'fe80::1771'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421771
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'mhr'
    wg:
      port: 22279
      endpoint: 'jp-nrt1.bb.mhr.hk:21023'
      wg_pubkey: 'Bt0gmHMrBBCgV8/k7n8ykA31YStGc55xmyLgMyB04E0='
      psk: null
      peer4: null
      peer6: 'fe80::2279'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242422279
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'sun'
    wg:
      port: 23088
      endpoint: 'v6.tyo1-jp.dn42.6700.cc:21023'
      wg_pubkey: 'b3gUz8an2+wSCvXAwuxGR7AnxKDUqqQMd1+LASo93R0='
      psk: null
      peer4: null
      peer6: 'fe80::3088:190'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423088
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'highdef.network'
    wg:
      port: 21080
      endpoint: 'tyo.peer.highdef.network:21023'
      wg_pubkey: 'iJXjwJGGrUTQy/P3OXmZ5lM4cjrDAd9K+vonZVUZjxY='
      psk: null
      peer4: null
      peer6: 'fe80::124'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421080
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'Nisbett'
    wg:
      port: 20398
      endpoint: 'nrt.dn42.boletus.icu:21023'
      wg_pubkey: 'QQecM/0eCbRu5TNdyRxGpJTCo6aGolMb0kZAqLH5Oho='
      psk: null
      peer4: null
      peer6: 'fe80::398'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420398
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'HExpNetwork'
    wg:
      port: 20298
      endpoint: 'node5.ox5.cc:21023'
      wg_pubkey: 'uGBAVsIQNZumBm7hb4l0cvCx3a2diQCUdb/o/PJPyis='
      psk: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        34303835663737333430313565323430663666353966633131323930633435663361356237613934
        6661623932306166613236616564333634326565333963300a643832343432306135316633656239
        30393739353864383935613361346664353532333161346234653137653763316464666165383438
        6237366439356236610a343032366330323037663765633963343432616561646539353962346439
        66363632396261396436353861356432366331313663393963313037313939343930333139376539
        3739386636643532663433623238373630353337363236323931
      peer4: null
      peer6: 'fe80::298'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420298
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'yuyuko'
    wg:
      port: 21117
      endpoint: 'jp01.dn42.yuyuko.com:21023'
      wg_pubkey: 'vZXB25Od9elWU4RKWp42MWNJrNtxJFgdmBkyYH/8Sj8='
      psk: null
      peer4: null
      peer6: 'fe80::1117'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421117
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'Minty'
    wg:
      port: 22172
      endpoint: 'jp.nodes.stella.observer:4242'
      wg_pubkey: 'Cbefg96Owv1Xk/jrUExO3i5OeUSlsdirv4ONenEnNXc='
      psk: null
      peer4: '172.20.193.67'
      peer6: 'fd55:dead:beef::3'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242422172
      ipv4: true
      ipv6: true
      extended_next_hop: false
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'RoutedBits'
    wg:
      port: 20207
      endpoint: 'router.tyo1.routedbits.com:51023'
      wg_pubkey: 'Urnj0In2/ba5zBJ0+TvGN6/A3JFXZwWfJ3EVkc5A4Cs='
      psk: null
      peer4: null
      peer6: 'fe80::207'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420207
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'moraxyc'
    wg:
      port: 23011
      endpoint: 'jp2.dn42.moraxyc.com:21023'
      wg_pubkey: '5Sq33dQ6Hox8lpda0wve08scNBc7BSDjaP4EPYKjdVk='
      psk: null
      peer4: null
      peer6: 'fe80::3011'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423011
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'launchpadx'
    wg:
      port: 23702
      endpoint: 'iij.s.launchpadx.top:51023'
      wg_pubkey: 'G5v93xQO15JtNMKJehB2HFMB/ACX0ec6u6EUFbKblBY='
      psk: null
      peer4: null
      peer6: 'fe80::3702'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423702
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'MoonWX'
    wg:
      port: 20985
      endpoint: 'dn42.jp01.moonwx.net:21023'
      wg_pubkey: 'bRDjdLlbPExg+q4Sqr+fCKYeHiMfIiTKCk6GolVXKho='
      psk: null
      peer4: null
      peer6: 'fe80::985:4'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420985
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'cloudc'
    wg:
      port: 23777
      endpoint: 'jp.cloudc.dev:21023'
      wg_pubkey: 'TRsJBPvVUXBCDuiBDwte+YCbkjkIglfVm+M5NxOFfwk='
      psk: null
      peer4: null
      peer6: 'fe80::3777'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423777
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'BingxinBaka'
    wg:
      port: 23374
      endpoint: 'jp01.dn42.baka.pub:21023'
      wg_pubkey: 'N7iQzqWLPb6lpRlf7grQG6rEzQOvDZWkmsRDkRnniH0='
      psk: null
      peer4: null
      peer6: 'fe80::2999:226'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423374
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'imlonghao'
    wg:
      port: 21888
      endpoint: 'jp1.dn42.ni.sb:21023'
      wg_pubkey: 'HND/VBClYdfCqAKGFmapwqOxg/KluPcv2u30rjD8+gk='
      psk: null
      peer4: null
      peer6: 'fe80::1888'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421888
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - wg:
      port: 20842
      endpoint: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        32623764646565353963393433326466326531323363343434306439643734326233353136376630
        3036616363376135643832636438646566633261656264360a393762616535393236316539373731
        38363839333065663432626665386435646633663538363139396139633965346632356531653664
        6664666332323534310a346265333965373330353433633635386334393039663766306639376161
        63313836636338326433656536663362356261323164366266633766343538373831
      wg_pubkey: 'ywWuEIEOiV6uSkllmhZ64BqXLkCyGJFhUKTfMyg+Y0A='
      psk: null
      peer4: '172.20.159.128'
      peer6: 'fe80::842'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420842
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    autopeer:
      managed: true
      effective_mnt: 'HEADSCARF175-MNT'
      auth_provider: 'registry_email'
