peers:
  - comment: 'factor2431'
    wg:
      port: 21534
      endpoint: 'jp-tyo.factor2431.com:21023'
      wg_pubkey: 'XYyk/uk3LTHk7vOqtDsDh/AcPtdT3qQptqhggzZCRio='
      psk: null
      peer4: null
      peer6: 'fe80::1534'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421534
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'tech9'
    wg:
      port: 21588
      endpoint: 'jp-tyo01.dn42.tech9.io:52923'
      wg_pubkey: 'unTYSat5YjkY+BY31Q9xLSfFhTUBvn3CiDCSZxbINVM='
      psk: null
      peer4: null
      peer6: 'fe80::1588'
      own6: 'fe80::100'
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421588
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'iyoroy'
    wg:
      port: 22024
      endpoint: 'ipv4.tyo-jp.ecs.iyoroy-infra.top:21023'
      wg_pubkey: 'Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4='
      psk: null
      peer4: null
      peer6: 'fe80::2024'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242422024
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'iedon'
    wg:
      port: 22189
      endpoint: 'jp-ty2.dn42.iedon.net:57739'
      wg_pubkey: 'XjKsLfOYJ8y/U9saLpfM/MjXErlQ7gkw3+OgQTdVZ0U='
      psk: null
      peer4: null
      peer6: 'fe80::2189:115'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242422189
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'lare'
    wg:
      port: 23035
      endpoint: 'jp01.dn42.lare.cc:21023'
      wg_pubkey: 'oTPdRylNhX2O80e6rLejT9Fwzo7KWKZ7a3PUF4G9oEM='
      psk: null
      peer4: null
      peer6: 'fe80::3035:134'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423035
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    removed: true
  - comment: 'cowgl'
    wg:
      port: 23999
      endpoint: 'tyo.node.cowgl.tech:31023'
      wg_pubkey: 'mMGGxtEqsagrx1Raw57C2H3Stl6ch/cUuF7y08eVgBE='
      psk: null
      peer4: null
      peer6: 'fe80::1:3999'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423999
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'Stevie'
    wg:
      port: 20337
      endpoint: 'tyo01.dn42.wwrr.ru:21023'
      wg_pubkey: 'xZBEeAO1btrRvU7cpXTBqaw8CZsmxrfB0005OgljtmU='
      psk: null
      peer4: null
      peer6: 'fe80::337'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420337
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'qiuxin'
    wg:
      port: 21771
      endpoint: 'tyo1.exploro.one:32619'
      wg_pubkey: 'MhxNjov4q8GjBFhDhSX4G8Zzx7/w4qbWw2RQSU5JDTU='
      psk: null
      peer4: null
      peer6: 'fe80::1771'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421771
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'mhr'
    wg:
      port: 22279
      endpoint: 'jp-nrt1.bb.mhr.hk:21023'
      wg_pubkey: 'Bt0gmHMrBBCgV8/k7n8ykA31YStGc55xmyLgMyB04E0='
      psk: null
      peer4: null
      peer6: 'fe80::2279'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242422279
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'sun'
    wg:
      port: 23088
      endpoint: 'v6.tyo1-jp.dn42.6700.cc:21023'
      wg_pubkey: 'b3gUz8an2+wSCvXAwuxGR7AnxKDUqqQMd1+LASo93R0='
      psk: null
      peer4: null
      peer6: 'fe80::3088:190'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423088
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'highdef.network'
    wg:
      port: 21080
      endpoint: 'tyo.peer.highdef.network:21023'
      wg_pubkey: 'iJXjwJGGrUTQy/P3OXmZ5lM4cjrDAd9K+vonZVUZjxY='
      psk: null
      peer4: null
      peer6: 'fe80::124'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421080
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'Nisbett'
    wg:
      port: 20398
      endpoint: 'nrt.dn42.boletus.icu:21023'
      wg_pubkey: 'QQecM/0eCbRu5TNdyRxGpJTCo6aGolMb0kZAqLH5Oho='
      psk: null
      peer4: null
      peer6: 'fe80::398'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420398
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'HExpNetwork'
    wg:
      port: 20298
      endpoint: 'node5.ox5.cc:21023'
      wg_pubkey: 'uGBAVsIQNZumBm7hb4l0cvCx3a2diQCUdb/o/PJPyis='
      psk: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        34303835663737333430313565323430663666353966633131323930633435663361356237613934
        6661623932306166613236616564333634326565333963300a643832343432306135316633656239
        30393739353864383935613361346664353532333161346234653137653763316464666165383438
        6237366439356236610a343032366330323037663765633963343432616561646539353962346439
        66363632396261396436353861356432366331313663393963313037313939343930333139376539
        3739386636643532663433623238373630353337363236323931
      peer4: null
      peer6: 'fe80::298'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420298
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'yuyuko'
    wg:
      port: 21117
      endpoint: 'jp01.dn42.yuyuko.com:21023'
      wg_pubkey: 'vZXB25Od9elWU4RKWp42MWNJrNtxJFgdmBkyYH/8Sj8='
      psk: null
      peer4: null
      peer6: 'fe80::1117'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421117
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'Minty'
    wg:
      port: 22172
      endpoint: 'jp.nodes.stella.observer:4242'
      wg_pubkey: 'Cbefg96Owv1Xk/jrUExO3i5OeUSlsdirv4ONenEnNXc='
      psk: null
      peer4: '172.20.193.67'
      peer6: 'fd55:dead:beef::3'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242422172
      ipv4: true
      ipv6: true
      extended_next_hop: false
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'RoutedBits'
    wg:
      port: 20207
      endpoint: 'router.tyo1.routedbits.com:51023'
      wg_pubkey: 'Urnj0In2/ba5zBJ0+TvGN6/A3JFXZwWfJ3EVkc5A4Cs='
      psk: null
      peer4: null
      peer6: 'fe80::207'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420207
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'moraxyc'
    wg:
      port: 23011
      endpoint: 'jp2.dn42.moraxyc.com:21023'
      wg_pubkey: '5Sq33dQ6Hox8lpda0wve08scNBc7BSDjaP4EPYKjdVk='
      psk: null
      peer4: null
      peer6: 'fe80::3011'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423011
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'launchpadx'
    wg:
      port: 23702
      endpoint: 'iij.s.launchpadx.top:51023'
      wg_pubkey: 'G5v93xQO15JtNMKJehB2HFMB/ACX0ec6u6EUFbKblBY='
      psk: null
      peer4: null
      peer6: 'fe80::3702'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423702
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'MoonWX'
    wg:
      port: 20985
      endpoint: 'dn42.jp01.moonwx.net:21023'
      wg_pubkey: 'bRDjdLlbPExg+q4Sqr+fCKYeHiMfIiTKCk6GolVXKho='
      psk: null
      peer4: null
      peer6: 'fe80::985:4'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420985
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'cloudc'
    wg:
      port: 23777
      endpoint: 'jp.cloudc.dev:21023'
      wg_pubkey: 'TRsJBPvVUXBCDuiBDwte+YCbkjkIglfVm+M5NxOFfwk='
      psk: null
      peer4: null
      peer6: 'fe80::3777'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423777
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'BingxinBaka'
    wg:
      port: 23374
      endpoint: 'jp01.dn42.baka.pub:21023'
      wg_pubkey: 'N7iQzqWLPb6lpRlf7grQG6rEzQOvDZWkmsRDkRnniH0='
      psk: null
      peer4: null
      peer6: 'fe80::2999:226'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423374
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - comment: 'imlonghao'
    wg:
      port: 21888
      endpoint: 'jp1.dn42.ni.sb:21023'
      wg_pubkey: 'HND/VBClYdfCqAKGFmapwqOxg/KluPcv2u30rjD8+gk='
      psk: null
      peer4: null
      peer6: 'fe80::1888'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242421888
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
  - wg:
      port: 20842
      endpoint: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        32623764646565353963393433326466326531323363343434306439643734326233353136376630
        3036616363376135643832636438646566633261656264360a393762616535393236316539373731
        38363839333065663432626665386435646633663538363139396139633965346632356531653664
        6664666332323534310a346265333965373330353433633635386334393039663766306639376161
        63313836636338326433656536663362356261323164366266633766343538373831
      wg_pubkey: 'ywWuEIEOiV6uSkllmhZ64BqXLkCyGJFhUKTfMyg+Y0A='
      psk: null
      peer4: '172.20.159.128'
      peer6: 'fe80::842'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420842
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    autopeer:
      managed: true
      effective_mnt: 'HEADSCARF175-MNT'
      auth_provider: 'registry_email'
  - wg:
      port: 20028
      endpoint: null
      wg_pubkey: 'FzUn0AkkCObJ+Kdn8YqkGopUZb1D9k0fwewnXCNB8Eg='
      psk: null
      peer4: '172.20.202.62'
      peer6: 'fdc1:e451:2020:9500::1'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420028
      ipv4: true
      ipv6: true
      extended_next_hop: false
      mp_bgp: false
    autopeer:
      managed: true
      effective_mnt: 'NGWORKS-MNT'
      auth_provider: 'registry_email'
  - wg:
      port: 22762
      endpoint: 'thighhighs.top:21023'
      wg_pubkey: '8hvGU6b0n16HIt63yarLIe6cEU/0+TdJXzej51jjxVo='
      psk: null
      peer4: null
      peer6: 'fe80::2762'
      own6: null
      keepalive: 61
      mtu: null
    bgp:
      asn: 4242422762
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    autopeer:
      managed: true
      effective_mnt: 'THIGHHIGHS-MNT'
      auth_provider: 'registry_email'
  - comment: 'node4 / NRT'
    wg:
      port: 23729
      endpoint: 'nrt1.pixiainfra.pixia.eu.org:21023'
      wg_pubkey: '7eD5aQ9LBHrxPabqMAGzCUIGLTRS1UGVD8A5X4pDgEI='
      psk: null
      peer4: '172.23.247.20'
      peer6: 'fe80::3729'
      own6: 'fe80::1023:2'
      keepalive: 25
      mtu: 1420
    bgp:
      asn: 4242423729
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    autopeer:
      managed: true
      effective_mnt: 'PIXIA-MNT'
      auth_provider: 'registry_pgp'
  - wg:
      port: 20083
      endpoint: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        62356532616130633435363733333237663862643034633566343838366666353631613432303930
        3062326661303133633133663238396439306366343636340a636338393536616532333966313163
        61663363353364653462353233313162643762326434323238613732666638666463666637666438
        3965373336643664370a343162353466333963326562663632366265343230333964343363613066
        31653063366533633162383563366134666134336130343233323236616136373237
      wg_pubkey: 'ztvNRxBT+AojkmGqmzhU4R2UWJz5ba8IvbEsCDhv0hw='
      psk: null
      peer4: null
      peer6: 'fe80::83'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420083
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    removed: true
    autopeer:
      managed: true
      effective_mnt: 'REDEARTH-MNT'
      auth_provider: 'iedon'
  - wg:
      port: 22363
      endpoint: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        35633134643139346531346236616434653936366435333735363031363463383461346563333361
        6465646538663935383935376363663834396134343639350a623633623230313361373634663937
        34653665366233656666396537313861393834386339343863396638313165653833316333656363
        3862383434376638660a656230373764666434613830313331663264373264353033623762336430
        64313738643665633962306430326635666361643466333263383637663266653430
      wg_pubkey: 'jK+5+Yrk8IRvZHDChqZkU3bwhdcxwiM5+nTuLl/mWhU='
      psk: null
      peer4: null
      peer6: 'fe80::ca73:2363:1023'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242422363
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    autopeer:
      managed: true
      effective_mnt: 'CHARLIEALEXANDER73-MNT'
      auth_provider: 'registry_pgp'
  - wg:
      port: 20706
      endpoint: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        34353665636239313962336564663234656633303037363136366436366639396339383163396434
        3033656637306663656461393462663932343734346366610a306231663366353737313931646331
        35356664633563386536373066383263313063626335366437363236383437383631383532613633
        3337373963353636350a333733366538363030646461633461626335323334333939366233396262
        62643162343634323734303230623134306433643536303765303035366433303934
      wg_pubkey: 'DGuMR7J1TMERIBoJ3tuJiI8cvHUyF84uQ7QwdhE26VI='
      psk: null
      peer4: null
      peer6: 'fe80::abcd'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420706
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    autopeer:
      managed: true
      effective_mnt: 'SILENTY4NG-MNT'
      auth_provider: 'registry_email'
  - wg:
      port: 20251
      endpoint: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        32663931326234663166383762613864353133613866363964633034323235323337346534613566
        3965653365353565663563653363353933343235353031330a323064663638613463383161633339
        65363933306337663433373538646364353733356330343637343966303430333464646335323639
        3232643264616336620a656530323265363037313837363131393631616263396437313863383939
        32646130336436396462656132303965366234623762363063386231363839303733
      wg_pubkey: 'JpoUAlk2vf4oojmVVIpiT7nCt5ufidJMCrAa+b6oWU8='
      psk: null
      peer4: '172.23.163.32'
      peer6: 'fe80::0251'
      own6: 'fe80::1023'
      keepalive: null
      mtu: null
    bgp:
      asn: 4242420251
      ipv4: true
      ipv6: true
      extended_next_hop: false
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    autopeer:
      managed: true
      effective_mnt: 'HANLIN-MNT'
      auth_provider: 'kioubit'
  - wg:
      port: 23380
      endpoint: '4.jp-nobrand.taroball.top:21023'
      wg_pubkey: 'ZUDgEIAcG5UblX0mkfB1aCyh8WxfLYs7ReNOd2W6Vm8='
      psk: null
      peer4: null
      peer6: 'fe80::4242:4233:8002'
      own6: null
      keepalive: null
      mtu: null
    bgp:
      asn: 4242423380
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
      mp_bgp_transport: 'ipv6'
    autopeer:
      managed: true
      effective_mnt: 'ZYK-MNT'
      auth_provider: 'kioubit'
