---
- name: Unarchive autopeer frontend assets
  ansible.builtin.unarchive:
    src: "{{ autopeer_frontend_tarball_path }}"
    dest: "{{ autopeer_frontend_root }}/"
    owner: www-data
    group: www-data

- name: Render autopeer frontend config
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ autopeer_frontend_root }}/config.json"
    owner: www-data
    group: www-data
    mode: "0644"
