---
- name: Prepare autopeer frontend deployment target
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Deploy autopeer frontend artifact
  ansible.builtin.include_tasks:
    file: configure.yaml
