---
bird_packages:
  - bird2

bird_repo_enabled: true
bird_repo_key_url: https://pkg.labs.nic.cz/gpg
bird_repo_key_path: /usr/share/keyrings/cznic-labs-pkg.gpg
bird_repo: deb [signed-by=/usr/share/keyrings/cznic-labs-pkg.gpg] https://pkg.labs.nic.cz/bird2 bookworm main
bird_repo_filename: cznic-labs-bird2

bird_rpki_servers:
  - host: rpki.akae.re
    port: 8082
  - host: rpki.dn42.launchpadx.top
    port: 8082

bird_rpki_refresh: 600
bird_rpki_retry: 300
bird_rpki_expire: 7200

bird_dn42_grc_enabled:
  - ams-01

dn42_latency_ping_count: 5
dn42_latency_ping_timeout: 2

dn42_latency_community_default: 9
dn42_bandwidth_community_default: 24
