---
network_name: IRIS-AS
asn: "4242421023"
network_comment: |
  Peering is welcome. All nodes support MP-BGP and IPv4 Extended Next Hop.
  s/svc.moe/iris.dn42/g for DN42 domains.
  Default port is the last 5 digits of the AS number (e.g., 4242421023 -> 21023).

network_contacts:
  Email: 0.0@owo.li
  Telegram: "@Iridoideae"

ownnet4: 172.21.111.64/26
ownnet6: fd42:4242:1023::/48

automation_user: dn42-automation
automation_root_dir: /opt/dn42
automation_user_home: /opt/dn42/automation/

bird_rpki_servers:
  - host: rpki.akae.re
    port: 8082
  - host: rpki.dn42.launchpadx.top
    port: 8082

bird_rpki_refresh: 600
bird_rpki_retry: 300
bird_rpki_expire: 7200

bird_dn42_grc_enabled:
  - ams-01

node_group: nodes
dn42_group: dn42

node_prefix: node_
dn42_prefix: dn42_

# by the time logging in at least one key should already work
ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJzmyIYtzsXMPZ5YxV6CTwM4ntgi8oSXNusH9Tqewkys"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHy+oWn8woMH2iYpcvAR+eeset79TIE6YJaUUM2F0Wlz"
  # this for GitHub Actions
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBEFpLa4DkkXQ0ZxHIwxCX4wGq4zKb797KEuHdBKsP0c"