---
dns_service:
  packages:
    - bind9
    - bind9utils
    - bind9-doc
  service_name: named
  user: bind
  group: bind
  config_dir: /etc/bind
  zone_dir: /etc/bind/zones

domain_name: iris.dn42
reverse_zone_ipv4: 64/26.111.21.172.in-addr.arpa
reverse_zone_ipv6: 3.2.0.1.2.4.2.4.2.4.d.f.ip6.arpa

dns_anycast_records:
  - name: ns1
    ipv4: 172.21.111.100
    ipv6: fd42:4242:1023::53:0
  - name: ns2
    ipv4: 172.21.111.101
    ipv6: fd42:4242:1023::53:1
  - name: anycast
    ipv4: 172.21.111.111
    ipv6: fd42:4242:1023::1111:1

dns_cname_records:
  - name: network
    target: anycast

dns_nameservers:
  - ns1
  - ns2

_dn42_forwarders: &dn42_forwarders
  - 172.20.0.53
  - fd42:d42:d42:54::1

_dns_allowed_clients: &dns_allowed_clients
  - 172.20.0.0/14
  - fd42::/16
  - 172.21.111.0/24
  - fd42:4242:1023::/48
  - 127.0.0.1
  - ::1

_soa_defaults: &soa_defaults
  primary_ns: ns1.iris.dn42.
  contact: hostmaster.iris.dn42.
  refresh: 7200
  retry: 3600
  expire: 1209600
  minimum: 3600

_transfer_defaults: &transfer_defaults
  - none

forward_zone_defaults:
  type: forward
  forward_policy: only
  forwarders: *dn42_forwarders

dns_named_options:
  directory: /var/cache/bind
  forwarders:
    - 9.9.9.9
    - 1.1.1.1
    - "2620:fe::fe"
    - "2606:4700:4700::1111"
  dnssec_validation: auto
  listen_on_v4:
    - 127.0.0.1
  listen_on_v6:
    - ::1
  allow_query: *dns_allowed_clients
  recursion: true
  allow_recursion: *dns_allowed_clients
  auth_nxdomain: false
  version: none
  extra_statements:
    - empty-zones-enable no;

dns_master_zones:
  - name: "{{ domain_name }}"
    ttl: 3600
    notify: true
    allow_transfer: *transfer_defaults
    allow_query:
      - any
    soa: *soa_defaults

  - name: "{{ reverse_zone_ipv4 }}"
    ttl: 3600
    notify: true
    allow_transfer: *transfer_defaults
    allow_query:
      - any
    soa: *soa_defaults

  - name: "{{ reverse_zone_ipv6 }}"
    ttl: 3600
    notify: true
    allow_transfer: *transfer_defaults
    allow_query:
      - any
    soa:
      <<: *soa_defaults

dns_extra_domains: []

dns_forward_zones_list:
  - dn42
  - 20.172.in-addr.arpa
  - 21.172.in-addr.arpa
  - 22.172.in-addr.arpa
  - 23.172.in-addr.arpa
  - 10.in-addr.arpa
  - d.f.ip6.arpa
