mxp-01:
  peers:
  - comment: RoutedBits
    wg:
      endpoint: router.mil1.routedbits.com:51023
      wg_pubkey: "3PKBRR7RmQcoIaO/66ulJVNgGqOsEYy2YIdHMuloQxE="
      peer6: fe80::207
    bgp:
      asn: 4242420207
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: PuduNet
    wg:
      endpoint: de01.pudunet.net:61023
      wg_pubkey: "V6gBK64MAL+BacO14xAaG/Z2l5tXmPWbWNj0Q8yCP0Q="
      peer6: fe80::2005
    bgp:
      asn: 4242422227
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true