tyo-01:
  peers:
  - comment: factor2431
    wg:
      port: 21534
      endpoint: jp-tyo.factor2431.com:21023
      wg_pubkey: "XYyk/uk3LTHk7vOqtDsDh/AcPtdT3qQptqhggzZCRio="
      peer4: null
      peer6: fe80::1534
      own6: null
      keepalive: null
    bgp:
      asn: 4242421534
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: tech9
    wg:
      endpoint: jp-tyo01.dn42.tech9.io:52923
      wg_pubkey: "unTYSat5YjkY+BY31Q9xLSfFhTUBvn3CiDCSZxbINVM="
      peer6: fe80::1588
      own6: fe80::100
    bgp:
      asn: 4242421588
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: iyoroy
    wg:
      endpoint: ipv4.tyo-jp.ecs.iyoroy-infra.top:21023
      wg_pubkey: "Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4="
      peer6: fe80::2024
    bgp:
      asn: 4242422024
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: iedon
    wg:
      endpoint: jp-ty2.dn42.iedon.net:57739
      wg_pubkey: "XjKsLfOYJ8y/U9saLpfM/MjXErlQ7gkw3+OgQTdVZ0U="
      peer6: fe80::2189:115
    bgp:
      asn: 4242422189
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: lare
    wg:
      endpoint: jp01.dn42.lare.cc:21023
      wg_pubkey: "oTPdRylNhX2O80e6rLejT9Fwzo7KWKZ7a3PUF4G9oEM="
      peer6: fe80::3035:134
    bgp:
      asn: 4242423035
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
    removed: true
  - comment: cowgl
    wg:
      endpoint: tyo.node.cowgl.xyz:31023
      wg_pubkey: "mMGGxtEqsagrx1Raw57C2H3Stl6ch/cUuF7y08eVgBE="
      peer6: fe80::1:3999
    bgp:
      asn: 4242423999
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: Stevie
    wg:
      endpoint: tyo01.dn42.wwrr.ru:21023
      wg_pubkey: "xZBEeAO1btrRvU7cpXTBqaw8CZsmxrfB0005OgljtmU="
      peer6: fe80::337
    bgp:
      asn: 4242420337
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: qiuxin
    wg:
      endpoint: tyo1.exploro.one:32619
      wg_pubkey: "MhxNjov4q8GjBFhDhSX4G8Zzx7/w4qbWw2RQSU5JDTU="
      peer6: fe80::1771
    bgp:
      asn: 4242421771
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: mhr
    wg:
      endpoint: jp-nrt1.bb.mhr.hk:21023
      wg_pubkey: "Bt0gmHMrBBCgV8/k7n8ykA31YStGc55xmyLgMyB04E0="
      peer6: fe80::2279
    bgp:
      asn: 4242422279
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: sun
    wg:
      endpoint: v6.tyo1-jp.dn42.6700.cc:21023
      wg_pubkey: "b3gUz8an2+wSCvXAwuxGR7AnxKDUqqQMd1+LASo93R0="
      peer6: fe80::3088:190
    bgp:
      asn: 4242423088
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: highdef.network
    wg:
      endpoint: tyo.peer.highdef.network:21023
      wg_pubkey: "iJXjwJGGrUTQy/P3OXmZ5lM4cjrDAd9K+vonZVUZjxY="
      peer6: fe80::124
    bgp:
      asn: 4242421080
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: Nisbett
    wg:
      endpoint: nrt.dn42.boletus.icu:21023
      wg_pubkey: "QQecM/0eCbRu5TNdyRxGpJTCo6aGolMb0kZAqLH5Oho="
      peer6: fe80::398
    bgp:
      asn: 4242420398
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: HExpNetwork
    wg:
      port: 20298
      endpoint: node5.ox5.cc:21023
      wg_pubkey: "uGBAVsIQNZumBm7hb4l0cvCx3a2diQCUdb/o/PJPyis="
      psk: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34303835663737333430313565323430663666353966633131323930633435663361356237613934
          6661623932306166613236616564333634326565333963300a643832343432306135316633656239
          30393739353864383935613361346664353532333161346234653137653763316464666165383438
          6237366439356236610a343032366330323037663765633963343432616561646539353962346439
          66363632396261396436353861356432366331313663393963313037313939343930333139376539
          3739386636643532663433623238373630353337363236323931
      peer6: fe80::298
    bgp:
      asn: 4242420298
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: yuyuko
    wg:
      endpoint: jp01.dn42.yuyuko.com:21023
      wg_pubkey: "vZXB25Od9elWU4RKWp42MWNJrNtxJFgdmBkyYH/8Sj8="
      peer6: fe80::1117
    bgp:
      asn: 4242421117
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: Minty
    wg:
      endpoint: jp.nodes.stella.observer:4242
      wg_pubkey: "Cbefg96Owv1Xk/jrUExO3i5OeUSlsdirv4ONenEnNXc="
      peer4: 172.20.193.67
      peer6: fd55:dead:beef::3
    bgp:
      asn: 4242422172
      ipv4: true
      ipv6: true
      extended_next_hop: false
      mp_bgp: true
  - comment: RoutedBits
    wg:
      endpoint: router.tyo1.routedbits.com:51023
      wg_pubkey: "Urnj0In2/ba5zBJ0+TvGN6/A3JFXZwWfJ3EVkc5A4Cs="
      peer6: fe80::207
    bgp:
      asn: 4242420207
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: moraxyc
    wg:
      endpoint: jp2.dn42.moraxyc.com:21023
      wg_pubkey: "5Sq33dQ6Hox8lpda0wve08scNBc7BSDjaP4EPYKjdVk="
      peer6: fe80::3011
    bgp:
      asn: 4242423011
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: launchpadx
    wg:
      endpoint: iij.s.launchpadx.top:51023
      wg_pubkey: "G5v93xQO15JtNMKJehB2HFMB/ACX0ec6u6EUFbKblBY="
      peer6: fe80::3702
    bgp:
      asn: 4242423702
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: MoonWX
    wg:
      endpoint: dn42.jp01.moonwx.net:21023
      wg_pubkey: "bRDjdLlbPExg+q4Sqr+fCKYeHiMfIiTKCk6GolVXKho="
      peer6: fe80::985:4
    bgp:
      asn: 4242420985
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: cloudc
    wg:
      endpoint: jp.cloudc.dev:21023
      wg_pubkey: "TRsJBPvVUXBCDuiBDwte+YCbkjkIglfVm+M5NxOFfwk="
      peer6: fe80::3777
    bgp:
      asn: 4242423777
      ipv4: false
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
