peers:
  - comment: HExpNetwork
    wg:
      endpoint: node2.ox5.cc:21023
      wg_pubkey: "pS0Xt7cbWU6Pjfq7+OCKQkpT9sSrI3y4gIUY8WdaLhM="
      psk: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        38663264393133316466336530396562336563353564333461373238356531633230323631663239
        3063313138366438646532306532363263666335636134650a363462653761333031393534313965
        63326231643633353161656536363039643737616539333165376437623532396339333363666236
        3537373164656236650a386537663266336465613735343639353635353266653765613334316135
        65396136383564626463633164643731373137623932646162626439623135343135306263346532
        3539623133636664636464316239393236366265303333386337
      peer6: fe80::298
    bgp:
      asn: 4242420298
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: Stevie
    wg:
      endpoint: hkg01.dn42.wwrr.ru:21023
      wg_pubkey: "jQAdLlfZ0mQBAAxIfSnltEBQQRIlf9/jMGWWPIOZY0Q="
      peer6: fe80::337
    bgp:
      asn: 4242420337
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: yuyuko
    wg:
      endpoint: hk01.dn42.yuyuko.com:21023
      wg_pubkey: "gqwdC9p6jdSy80oRxdatr9QdSrNMLCvRMadaCeOBqDY="
      peer6: fe80::1117
    bgp:
      asn: 4242421117
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: iedon
    wg:
      endpoint: hk-hkg.dn42.iedon.net:47122
      wg_pubkey: "OlUDuWkUI9pKNsNo7Vjf/GKKVSBslh9kmqjbeYA4+34="
      peer6: fe80::2189:120
    bgp:
      asn: 4242422189
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
    removed: true
  - comment: potat0
    wg:
      endpoint: hkg.node.potat0.cc:21023
      wg_pubkey: "Tv1+HniELrS4Br2i7oQgwqBJFXQKculsW8r+UOqQXH0="
      peer6: fe80::1816
    bgp:
      asn: 4242421816
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: iyoroy
    wg:
      endpoint: hkg02-cn.ecs.iyoroy-infra.top:21023
      wg_pubkey: "bg+KnzVupBrOQntHFFVzvBx+3sqYVoyJRantT6m5fm8="
      peer6: fe80::2024
    bgp:
      asn: 4242422024
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: BingxinBaka
    wg:
      endpoint: hk01.dn42.baka.pub:21023
      wg_pubkey: "zcxhWeI3SrJtqlHuqdeNaCeWSwJIYOTjAraXm655+VY="
      peer6: fe80::2999:225
    bgp:
      asn: 4242423374
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: cowgl
    wg:
      endpoint: v6.hkg.node.cowgl.xyz:31023
      wg_pubkey: "mGGBczSVKW+7UKRquI2GkbKrfxiATv9r4uF5WTP+vWI="
      peer6: fe80::3999
    bgp:
      asn: 4242423999
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: qiuxin
    wg:
      endpoint: hkg1.exploro.one:32615
      wg_pubkey: "hsEWaH80s3f0+PNsfLbyHUnFTNOwdqoJMHHyhOUqdFs="
      peer6: fe80::1771
    bgp:
      asn: 4242421771
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: mhr
    wg:
      endpoint: 6.hk-hkg1.bb.mhr.hk:21023
      wg_pubkey: "PUjqyQ3ATLp8Cxp3YFVQ44QLoZEpoPgdXsbMfXhDMRk="
      peer6: fe80::2279
    bgp:
      asn: 4242422279
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: darkpoint
    wg:
      endpoint: sin.darkpoint.xyz:21023
      wg_pubkey: "LbAFxxPonoNUzWiaxa/ulNYfv0d729DG6qAmg2X5egc="
      peer6: fe80::150
    bgp:
      asn: 4242420150
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
    removed: true
  - comment: sun
    wg:
      endpoint: v6.hk1-hk.dn42.6700.cc:21023
      wg_pubkey: "rBTH+JyZB0X/DkwHByrCjCojxBKr/kEOm1dTAFGHR1w="
      peer6: fe80::3088:192
    bgp:
      asn: 4242423088
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: factor2431
    wg:
      endpoint: hk-hkg.factor2431.com:21023
      wg_pubkey: "VncCNj0rfJ8xF4ms7yqvt+WzAS0ePC+pLiiG4FPPHkw="
      peer6: fe80::1534
    bgp:
      asn: 4242421534
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: highdef.network
    wg:
      endpoint: hkg.peer.highdef.network:21023
      wg_pubkey: "eedTHubyl5caiHH50GkknQa8SQtAF8q7aqmL26w5qSs="
      peer6: fe80::1080:38
    bgp:
      asn: 4242421080
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: kioubit
    wg:
      endpoint: hk1.g-load.eu:21023
      wg_pubkey: "sLbzTRr2gfLFb24NPzDOpy8j09Y6zI+a7NkeVMdVSR8="
      psk: null
      peer4: null
      peer6: fe80::ade0
    bgp:
      asn: 4242423914
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: Nisbett
    wg:
      endpoint: hkl.dn42.boletus.icu:21023
      wg_pubkey: "XD66eoHp06VmDUNFUguJeOY8gFLiLZ7Lkyz/WsMQSWU="
      peer6: fe80::398
    bgp:
      asn: 4242420398
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: Maraun
    wg:
      endpoint: dn42-sg.maraun.de:21023
      wg_pubkey: "rWTIK93+XJaP4sRvrk1gqXxAZgkz6y/axLC4mjuay1I="
      peer6: fe80::2225
      own6: fe80::1023
    bgp:
      asn: 4242422225
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: tech9
    wg:
      endpoint: sg-sin01.dn42.tech9.io:51143
      wg_pubkey: "4qLIJ9zpc/Xgvy+uo90rGso75cSrT2F5tBEv+6aqDkY="
      peer6: fe80::1588
      own6: fe80::100
    bgp:
      asn: 4242421588
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: RoutedBits
    wg:
      endpoint: router.sin1.routedbits.com:51023
      wg_pubkey: "8sTnWN7ykPaDe1WIZOlnqECiGMJzwXB8TXWHcT7qnEw="
      peer6: fe80::207
    bgp:
      asn: 4242420207
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: allnet
    wg:
      endpoint: 156.226.173.78:21023
      wg_pubkey: "krJb3l8hypXbDs8h6zNw5QQy5zdwVsRKRm1g30KnYBU="
      peer6: fe80::387
    bgp:
      asn: 4242420387
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: moraxyc
    wg:
      endpoint: hk4.dn42.moraxyc.com:21023
      wg_pubkey: "VLapquicGRZmdMAamgQ19jyo7LbmK3X3nNCffGo6ID4="
      peer6: fe80::3011
    bgp:
      asn: 4242423011
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: MoonWX
    wg:
      endpoint: 6.dn42.hk01.moonwx.net:21023
      wg_pubkey: "NfLhJvm5GiJ7emKFtRRLMM68H+tAkzSVrOAqfQJY1Ts="
      peer6: fe80::985:1
      mtu: 1340
    bgp:
      asn: 4242420985
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: PuduNet
    wg:
      endpoint: sin01.pudunet.net:61023
      wg_pubkey: "prifvN1CEXmuOAM3I1ykzaa6vD97Hy84j4Ag99x9CmA="
      peer6: fe80::2003
    bgp:
      asn: 4242422227
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: leziblog
    wg:
      endpoint: v6.hk1.peer.dn42.leziblog.com:21023
      wg_pubkey: "XaX6/G7EQbcjsrtlxNmDc/s/VSdTxtkBxZKB2JpWIHo="
      peer6: fe80::3377
    bgp:
      asn: 4242423377
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: "@Auride"
    wg:
      endpoint: hkg01.edge.r1.tmpfs.dev:21023
      wg_pubkey: "aC9pjzMWZhbA/sLPljUFGU1K28MSopHbKNj5yyv4uzg="
      peer6: fe80::1023:3310
      mtu: 1420
    bgp:
      asn: 4242423310
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: nedifinita
    wg:
      endpoint: dn42hk0.nedifinita.com:56689
      wg_pubkey: "8auu/+HFce5JAexe1b5MDg+nh4vutQVlXd0kJySXVGc="
      peer6: fe80::454:112
    bgp:
      asn: 4242420454
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: "imlonghao"
    wg:
      endpoint: hk1.dn42.ni.sb:21023
      wg_pubkey: "RyP2/n///CanKOD1EFtiPawHfUZb14+Fg0v4pbpsrnY="
      peer6: fe80::1888
    bgp:
      asn: 4242421888
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: "vctop"
    wg:
      endpoint: hk.node.vconet.top:21023
      wg_pubkey: "AHEJ0dXDDxJF0EapR7Ssx2eQV9ReB/OvkWPu7ypWbkA="
      peer6: fe80::3322
    bgp:
      asn: 4242423322
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
  - comment: Kaede
    wg:
      endpoint: hkg1.hk.dn42.akinokaede.com:21023
      wg_pubkey: "ZCTsAWqaiEnrmtX/2j9YNgB1vQ4HnodFtI9m/lwQLnU="
      peer6: fe80::2212
    bgp:
      asn: 4242422212
      ipv4: true
      ipv6: true
      extended_next_hop: true
      mp_bgp: true
