---
caddy_packages:
  - caddy

caddy_repo_key_url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
caddy_repo_key_path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
caddy_repo_key_asc_path: "{{ caddy_repo_key_path }}.asc"
caddy_repo: deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
caddy_repo_filename: caddy-stable

dn42_acme_directory: https://acme.burble.dn42/v1/dn42/acme/directory
network_site_root: /var/www/html/network.iris.dn42

caddy_dns_plugins:
  - github.com/caddy-dns/rfc2136

caddy_dns01_rfc2136_server: "{{ hostvars[dns_zone_primary].ownip }}:53"
caddy_dns01_tsig_key_name: "{{ dns_tsig_key_name }}"
caddy_dns01_tsig_key_algo: "{{ dns_tsig_key_algo }}"
caddy_dns01_tsig_key_value: "{{ dns_tsig_key_secret | regex_search('secret \"([^\"]+)\"', '\\1') | first }}"
