---
- name: Get current commit hash for bird-lg-rs
  ansible.builtin.command: git rev-parse HEAD
  args:
    chdir: "{{ playbook_dir }}/bird-lg-rs"
  delegate_to: localhost
  become: false
  run_once: true
  register: lg_build_current_commit
  changed_when: false

- name: Read last built commit hash for {{ lg_binary_name }}
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/{{ lg_build_stamp_file }}"
  delegate_to: localhost
  become: false
  run_once: true
  register: lg_build_last_commit
  ignore_errors: true

- name: Build {{ lg_binary_name }} binary
  when: (lg_build_last_commit.failed | default(true)) or (lg_build_last_commit.content | b64decode | trim != lg_build_current_commit.stdout)
  block:
    - name: Run cargo build for {{ lg_binary_name }}
      ansible.builtin.command:
        cmd: "cargo zigbuild --target x86_64-unknown-linux-musl -p {{ lg_cargo_package }} -r"
        chdir: "{{ playbook_dir }}/bird-lg-rs"
      delegate_to: localhost
      become: false
      run_once: true
      changed_when: true

    - name: Save current commit hash for {{ lg_binary_name }}
      ansible.builtin.copy:
        content: "{{ lg_build_current_commit.stdout }}"
        dest: "{{ playbook_dir }}/{{ lg_build_stamp_file }}"
        mode: "0644"
      delegate_to: localhost
      become: false
      run_once: true
