---
- name: Cleanup Looking Glass configuration
  ansible.builtin.include_tasks:
    file: cleanup.yaml
  when: remove_node | default(false)

- name: End play if removing node
  ansible.builtin.meta: end_host
  when: remove_node | default(false)

- name: Create lg workspace
  ansible.builtin.file:
    path: "{{ automation_root_dir }}/lg"
    state: directory
    owner: "{{ automation_user }}"
    group: nogroup
    mode: "0755"

- name: Configure Looking Glass proxy component
  ansible.builtin.include_tasks:
    file: proxy.yaml
  when:
    - target is undefined
    - lg_configure_proxy | default(false)

- name: Configure Looking Glass server component
  ansible.builtin.include_tasks:
    file: server.yaml
  when:
    - target is undefined
    - lg_configure_server | default(false)
