---
- name: Gather WireGuard node list
  ansible.builtin.set_fact:
    node_hosts: "{{ groups.get(node_group, []) | list }}"

- name: Compute WireGuard ordering for this node
  ansible.builtin.set_fact:
    wg_node_self_order: "{{ node_hosts.index(inventory_hostname) + 1 }}"

- name: Ensure PSK directory exists on controller
  become: false
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.secrets/wireguard_psks/{{ node_group }}"
    state: directory
    mode: "0700"
  delegate_to: localhost
  run_once: true

- name: Generate WireGuard PSKs on controller
  become: false
  ansible.builtin.shell:
    cmd: |
      if [ ! -f "{{ playbook_dir }}/.secrets/wireguard_psks/{{ node_group }}/psk_{{ item.0 }}_{{ item.1 }}.key" ]; then
        wg genpsk > "{{ playbook_dir }}/.secrets/wireguard_psks/{{ node_group }}/psk_{{ item.0 }}_{{ item.1 }}.key"
        chmod 600 "{{ playbook_dir }}/.secrets/wireguard_psks/{{ node_group }}/psk_{{ item.0 }}_{{ item.1 }}.key"
      fi
      cat "{{ playbook_dir }}/.secrets/wireguard_psks/{{ node_group }}/psk_{{ item.0 }}_{{ item.1 }}.key"
  delegate_to: localhost
  loop: "{{ node_hosts | product(node_hosts) | list }}"
  loop_control:
    label: "{{ item.0 }} -> {{ item.1 }}"
  when:
    - item.0 < item.1
    - item.0 != item.1
  register: wg_psk_generation
  changed_when: false
  no_log: true
  run_once: true

- name: Parse WireGuard PSKs for this host
  ansible.builtin.set_fact:
    wg_peer_psks: >-
      {{ wg_peer_psks | default({}) | combine({
        (item.item.0 if inventory_hostname == item.item.1 else item.item.1): item.stdout
      }) }}
  loop: "{{ wg_psk_generation.results }}"
  loop_control:
    label: "{{ item.item.0 }} -> {{ item.item.1 }}"
  when:
    - item.skipped is not defined or not item.skipped
    - item.stdout is defined
    - inventory_hostname == item.item.0 or inventory_hostname == item.item.1

- name: Build WireGuard peer descriptors
  ansible.builtin.set_fact:
    wg_node_peers_configure: "{{ (wg_node_peers_configure | default([])) + [peer_entry] }}"
  vars:
    peer_hostvars: "{{ hostvars[peer] | default({}) }}"
    # TODO: read local one
    peer_public_key: >-
      {{ (peer_hostvars.wg_pubkey if peer_hostvars.wg_pubkey is defined
         else (peer_hostvars.wireguard_public_key | mandatory )) }}
    peer_entry:
      name: "{{ peer }}"
      interface_name: "{{ node_prefix }}{{ peer | replace('-', '_') }}"
      peer_order: "{{ node_hosts.index(peer) + 1 }}"
      endpoint_host: "{{ peer_hostvars.ansible_host | mandatory }}"
      public_key: "{{ peer_public_key }}"
      preshared_key: "{{ wg_peer_psks[peer] }}"
  loop: "{{ node_hosts }}"
  loop_control:
    loop_var: peer
    label: "{{ peer }}"
  when:
    - peer != inventory_hostname
    - >-
      (ip_support | default('dual') == 'dual') or
      (peer_hostvars.ip_support | default('dual') == 'dual') or
      (ip_support | default('dual') == peer_hostvars.ip_support | default('dual'))
    - target is undefined or
      target == (node_prefix ~ peer | replace('-', '_')) or
      target == (node_prefix ~ inventory_hostname | replace('-', '_'))

- name: Filter WireGuard peers for removal
  ansible.builtin.set_fact:
    wg_node_peers_remove: >-
      {{
        wg_node_peers_configure | default([])
        if (remove | default(false))
        else []
      }}
    wg_node_peers_configure: >-
      {{
        []
        if (remove | default(false))
        else wg_node_peers_configure | default([])
      }}

- name: Render per-peer WireGuard configurations
  ansible.builtin.template:
    src: node_tunnel.conf.j2
    dest: "/etc/wireguard/{{ peer.interface_name }}.conf"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ wg_node_peers_configure | default([]) }}"
  loop_control:
    loop_var: peer
    label: "{{ peer.name }}"
  register: node_peer_templates

- name: Remove per-peer WireGuard configurations
  ansible.builtin.file:
    path: "/etc/wireguard/{{ peer.interface_name }}.conf"
    state: absent
  loop: "{{ wg_node_peers_remove | default([]) }}"
  loop_control:
    loop_var: peer
    label: "{{ peer.name }}"
  register: node_peer_removals

- name: Set fact for rendered WireGuard peers
  ansible.builtin.set_fact:
    wg_rendered_peers: >-
      {{ (wg_rendered_peers | default([])) + node_peer_templates.results }}
  when: node_peer_templates is defined

- name: Set fact for removed WireGuard peers
  ansible.builtin.set_fact:
    wg_removed_peers: >-
      {{ (wg_removed_peers | default([])) + node_peer_removals.results }}
  when: node_peer_removals is defined
