---
- name: Ensure Looking Glass server workspace exists
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Configure Looking Glass server
  ansible.builtin.include_tasks:
    file: configure.yaml
