---
- name: Cleanup Looking Glass server configuration
  ansible.builtin.include_tasks:
    file: cleanup.yaml
  when: remove_node | default(false)

- name: End play if removing node
  ansible.builtin.meta: end_host
  when: remove_node | default(false)

- name: Ensure Looking Glass server workspace exists
  ansible.builtin.include_tasks:
    file: install.yaml
  when: not (remove | default(false))

- name: Configure Looking Glass server
  ansible.builtin.include_tasks:
    file: configure.yaml
  when: not (remove | default(false))
