---
- name: Configure Prometheus node exporters
  hosts: nodes
  become: true
  gather_facts: true
  tags:
    - prometheus-exporter
  roles:
    - role: config-prometheus-exporter
      tags:
        - prometheus-exporter
    - role: config-prometheus-wireguard-exporter
      tags:
        - prometheus-wireguard-exporter

- name: Configure Prometheus BIRD exporter
  hosts: dn42
  become: true
  gather_facts: true
  tags:
    - prometheus-bird-exporter
  roles:
    - role: config-prometheus-bird-exporter
      tags:
        - prometheus-bird-exporter

- name: Configure Prometheus monitoring server node exporter
  hosts: monitoring_server
  become: true
  gather_facts: true
  tags:
    - prometheus-exporter
  roles:
    - role: config-prometheus-exporter
      tags:
        - prometheus-exporter

- name: Configure Prometheus server
  hosts: monitoring_server
  become: false
  gather_facts: true
  tags:
    - prometheus-server
  roles:
    - role: config-prometheus-server
      tags:
        - prometheus-server
