---
- name: System Configuration
  hosts: nodes
  become: true
  gather_facts: true
  tags:
    - system
  roles:
    - role: config-apt
      tags:
        - apt-preflight
    - role: config-system
      tags:
        - system
