# /etc/bird/babel.conf
# Managed by Ansible

protocol babel internal_mesh {
    ipv4 {
        import where source != RTS_BGP && is_self_net();
        export where source != RTS_BGP && is_self_net();
    };
    ipv6 {
        import where source != RTS_BGP && is_self_net_v6();
        export where source != RTS_BGP && is_self_net_v6();
    };
    interface "node_*" {
        type tunnel;

        rxcost 16;
        rtt cost 768;
        rtt max 500 ms;
        rtt min 1 ms;
        rtt decay 42;

        check link on;
    };
}
