# /etc/bird/bird.conf
# Managed by Ansible

include "/etc/bird/node.conf";

log syslog all;
router id OWNIP;
hostname OWNHOSTNAME;

include "/etc/bird/dn42_communities.conf";

roa4 table dn42_roa;
roa6 table dn42_roa_v6;

include "/etc/bird/dn42_filters.conf";

protocol device {
    scan time 10;
}

protocol direct {
    ipv4;
    ipv6;
    interface "dn42-dummy", "node_*", "dn42_*", "lo";
}

protocol kernel {
    scan time 20;

    ipv6 {
        import none;
        export filter {
            if source = RTS_STATIC then reject;
            krt_prefsrc = OWNIPv6;
            accept;
        };
    };

    merge paths on;
};

protocol kernel {
    scan time 20;

    ipv4 {
        import none;
        export filter {
            if source = RTS_STATIC then reject;
            krt_prefsrc = OWNIP;
            accept;
        };
    };

    merge paths on;
}

protocol static {
    route OWNNET reject;
    route OWNNODENET reject;

    ipv4 { import all; export none; };
}

protocol static {
    route OWNNETv6 reject;
    route OWNNODENETv6 reject;

    ipv6 { import all; export none; };
}

include "/etc/bird/rpki.conf";
include "/etc/bird/babel.conf";

template bgp dnpeers {
    local as OWNAS;
    path metric 1;
    advertise hostname on;

    hold time 90;
    keepalive time 30;

    ipv4 {
        import filter {
          if is_valid_network() && !is_self_net() then {
            if (roa_check(dn42_roa, net, bgp_path.last) != ROA_VALID) then {
              print "[dn42] ROA check failed for ", net, " ASN ", bgp_path.last;
              reject;
            } else accept;
          } else reject;
        };

        export filter { 
          if is_valid_network() && source ~ [RTS_STATIC, RTS_BGP] then {
            accept;
          } else reject; 
        };
        import limit 9000 action block;
    };

    ipv6 {   
        import filter {
          if is_valid_network_v6() && !is_self_net_v6() then {
            if (roa_check(dn42_roa_v6, net, bgp_path.last) != ROA_VALID) then {
              print "[dn42] ROA check failed for ", net, " ASN ", bgp_path.last;
              reject;
            } else accept;
          } else reject;
        };

        export filter { 
            if is_self_net_v6() && net != OWNNETv6 then reject;

            if is_valid_network_v6() && source ~ [RTS_STATIC, RTS_BGP] then {
                accept;
            } else reject; 
        };
        import limit 9000 action block; 
    };
}

template bgp internal_bgp {
    local as OWNAS;

    advertise hostname on;
    require hostname on;

    multihop;
    enable extended messages on;

    ipv4 {
        extended next hop on; 
        gateway recursive; 
        
        import where source = RTS_BGP && is_valid_network() && !is_self_net();
        export where source = RTS_BGP 
                     && is_valid_network() 
                     && !is_self_net() 
                     && bgp_path.len > 0;        
        next hop self;
        add paths rx;
    };

    ipv6 {
        gateway recursive;
        import where source = RTS_BGP && is_valid_network_v6() && !is_self_net_v6();
        export where source = RTS_BGP 
                     && is_valid_network_v6() 
                     && !is_self_net_v6() 
                     && bgp_path.len > 0;
        next hop self;
        add paths rx;
    };
}

include "/etc/bird/dn42_misc.conf";
include "/etc/bird/peers/*";
include "/etc/bird/nodes/*";
