---
- name: Fetch Caddy signing key
  ansible.builtin.uri:
    url: "{{ apt_preflight_caddy_repo_key_url }}"
    return_content: true
  register: apt_preflight_caddy_key_response
  changed_when: false

- name: Check current armored Caddy signing key
  ansible.builtin.stat:
    path: "{{ apt_preflight_caddy_repo_key_asc_path }}"
    checksum_algorithm: sha256
  register: apt_preflight_caddy_key_asc_stat

- name: Check current dearmored Caddy signing key
  ansible.builtin.stat:
    path: "{{ apt_preflight_caddy_repo_key_path }}"
  register: apt_preflight_caddy_key_stat

- name: Update armored Caddy signing key
  ansible.builtin.copy:
    content: "{{ apt_preflight_caddy_key_response.content }}"
    dest: "{{ apt_preflight_caddy_repo_key_asc_path }}"
    mode: "0644"
  register: apt_preflight_caddy_key_copy
  when:
    - not apt_preflight_caddy_key_asc_stat.stat.exists
      or apt_preflight_caddy_key_asc_stat.stat.checksum !=
      (apt_preflight_caddy_key_response.content | hash('sha256'))

- name: Dearmor Caddy signing key
  ansible.builtin.command:
    argv:
      - gpg
      - --dearmor
      - --yes
      - --output
      - "{{ apt_preflight_caddy_repo_key_path }}"
      - "{{ apt_preflight_caddy_repo_key_asc_path }}"
  when:
    - apt_preflight_caddy_key_copy is changed
      or not apt_preflight_caddy_key_stat.stat.exists
